server:
  port: 81
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/takeaway?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456